baseURL = 'https://playpixellabs.github.io/'
languageCode = 'en-us'
title = 'PlayPixelLabs'

# theme = "" # We are using direct layouts, not a separate theme

# Enable JSON output for the search index
[outputs]
  home = ["HTML", "RSS"]

# hugo.toml

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Set this to true to allow raw HTML in your Markdown files.
      # Be careful with this setting if you have untrusted content.
      unsafe = true
  [markup.highlight]
    # ==> Method 1: Inline Styles (easiest)
    # The default is 'true', which uses inline styles.
    # No extra CSS file is needed, but HTML files are larger.
    noClasses = false

    # ==> Method 2: CSS Classes (recommended for performance)
    # If you set this to 'false', you must generate a syntax CSS file.
    # See Step 3 for instructions.
    # noClasses = false

    # Choose a color theme.
    # See the full list at: [https://xyproto.github.io/splash/docs/all.html](https://xyproto.github.io/splash/docs/all.html)
    # Popular themes: dracula, monokai, github, friendly, nord
    style = 'dracula'

    # Show line numbers globally. Can be overridden per code block.
    lineNos = false

    # Enable standard Markdown code fences.
    codeFences = true

    # Guess syntax for code blocks without a language specified.
    guessSyntax = false


[mediaTypes."application/json"]
  suffixes = ["json"]

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "search" # This will create search.json

# Configure taxonomies (categories and tags)
[taxonomies]
  category = "categories"
  tag = "tags"
  subject = "subjects"
  keyword = "keywords"

[params]
  description = "The best collection of quick, lightweight browser games."
  keywords = ["games", "browser", "casual"]
  author = "PlayPixelLabs"
  image = "https://yt3.googleusercontent.com/3FLMvdMbKO73nwGgYJ2ajLJfZ2eoao7d5dwiPEWD6vtWS4yWXzs3OpGnRkl0ELpKki3VCz2C8-8=w1060-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj"
  googleAnalyticsID = "G-XXXXXXXXXX" # Replace with your actual Google Analytics ID