baseURL = 'https://playpixellabs.github.io/'
languageCode = 'en-us'
title = 'PlayPixelLabs'

# theme = "" # We are using direct layouts, not a separate theme

# Enable JSON output for the search index
[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    # See https://xyproto.github.io/splash/docs/ for theme gallery
    style = "dracula"
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = false
    # Other available options:
    # anchorLineNos = true
    # lineNumbersInTable = true
    # tabWidth = 4


[mediaTypes."application/json"]
  suffixes = ["json"]

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "search" # This will create search.json

# Configure taxonomies (categories and tags)
[taxonomies]
  category = "categories"
  tag = "tags"
  subject = "subjects"
  keyword = "keywords"

[params]
  description = "The best collection of quick, lightweight browser games."
  keywords = ["games", "browser", "casual"]
  author = "PlayPixelLabs"
  image = "https://yt3.googleusercontent.com/3FLMvdMbKO73nwGgYJ2ajLJfZ2eoao7d5dwiPEWD6vtWS4yWXzs3OpGnRkl0ELpKki3VCz2C8-8=w1060-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj"
  googleAnalyticsID = "G-XXXXXXXXXX" # Replace with your actual Google Analytics ID